<?php

namespace Drupal\y_lb\Form;

use Drupal\Core\Form\FormStateInterface;
use Drupal\layout_builder\Form\DefaultsEntityForm;
use Drupal\layout_builder\SectionStorageInterface;

class YLBEntityViewDisplay extends DefaultsEntityForm {

  public function buildForm(array $form, FormStateInterface $form_state, SectionStorageInterface $section_storage = NULL) {
    $settings = $this->entity->getThirdPartySettings('y_lb');

    $form['ws_design_settings'] = [
      '#type' => 'ws_theme_select',
      '#value' => $settings['settings']
    ];

    return parent::buildForm($form, $form_state, $section_storage); // TODO: Change the autogenerated stub
  }

  public function save(array $form, FormStateInterface $form_state) {

    $this->entity->setThirdPartySetting('y_lb', 'settings', $form_state->getUserInput()['ws_design_settings']);
    return parent::save($form, $form_state); // TODO: Change the autogenerated stub
  }

}
